FROM alpine:latest

ENV APP_HOME /app
ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

COPY . $APP_HOME
WORKDIR $APP_HOME

RUN apk -X http://dl-cdn.alpinelinux.org/alpine/v3.7/main -X http://dl-cdn.alpinelinux.org/alpine/v3.7/community add --no-cache ruby=2.4.5-r0 ruby-dev=2.4.5-r0 build-base && gem install bundler --no-ri --no-rdoc && rm -rf /var/lib/apk/* && bundle install && rm -rf /root/.bundle

CMD ["puma"]

