---
 - name: Creates gitlab-runner config directory
   file:
     path: /srv/gitlab-runner-{{ item }}/config
     state: directory
   loop: "{{ query('sequence', 'start=1 end={{ n_of_runners }}') }}"
   
