---
- name: Create gitlab-runner container
  docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest

- name: Run container
  docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    state: started
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  tags: gitlab-runner-run

- name: Run gitlab-runner
  command: docker exec gitlab-runner gitlab-runner register --non-interactive --url http://"{{ gitlab_ip }}" --registration-token "{{ gitlab_token }}" --executor docker --docker-image aline:latest --name runner-"{{ ansible_hostname }}" --locked False --run-untagged True
  become: true
  tags: gitlab-runner-run

