version: '2'
services:

  awx_web:
    image: ansible/awx_web:2.1.2
    depends_on:
      - awx_rabbitmq
      - awx_memcached
      - awx_postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SECRET_KEY: awxsecret
      DATABASE_NAME: awx
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_PORT: 5432
      DATABASE_HOST: awx_postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: awx_rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: awx_memcached
      MEMCACHED_PORT: 11211
      AWX_ADMIN_USER: admin
      AWX_ADMIN_PASSWORD: password
    networks:
      awx_net:
      mgm_net:
        aliases:
          - awx-web
      

  awx_task:
    image: ansible/awx_task:2.1.2
    depends_on:
      - awx_rabbitmq
      - awx_memcached
      - awx_web
      - awx_postgres
    hostname: awx
    user: root
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SECRET_KEY: awxsecret
      DATABASE_NAME: awx
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_HOST: awx_postgres
      DATABASE_PORT: 5432
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: awx_rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: awx_memcached
      MEMCACHED_PORT: 11211
      AWX_ADMIN_USER: admin
      AWX_ADMIN_PASSWORD: password
    networks:
      - awx_net

  awx_rabbitmq:
    image: ansible/awx_rabbitmq:3.7.4
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: awx
      RABBITMQ_ERLANG_COOKIE: cookiemonster
    networks:
      - awx_net

  awx_memcached:
    image: memcached:alpine
    restart: unless-stopped
    networks:
      - awx_net

  awx_postgres:
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - awx_pg_data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - awx_net

volumes:
  awx_pg_data:

networks:
  awx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.20.0/24
  mgm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24

