version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    image: elasticsearch:6.5.0
    expose:
      - 9200
    ports:
      - 9200:9200

  kibana:
    image: kibana:6.5.0
    ports:
      - 5601:5601

  zipkin:
    image: openzipkin/zipkin:2.11.8
    ports:
      - 9411:9411
    networks:
      - front_net
      - back_net

networks:
  front_net:
  back_net:

