version: '3'
services:

  post_db:
    image: mongo:$post_db_version
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
          aliases:
            - $app_post_db
            - $app_comment_db
      mgm_net:
        aliases:
            - post_db_mgmt

  ui:
    image: ${USERNAME}/ui:$ui_version
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - $external_ui_port:$internal_ui_port/tcp
    networks:
      front_net:
          aliases:
            - $app_ui
      mgm_net:
        aliases:
            - ui_mgmt
    logging:
      driver: "fluentd"
      options: 
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USERNAME}/post:$post_version
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
          aliases:
            - $app_post
      back_net:
          aliases:
            - $app_post
      mgm_net:
        aliases:
            - post_mgmt
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USERNAME}/comment:$comment_version
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
          aliases:
            - $app_comment
      back_net:
          aliases:
            - $app_comment
      mgm_net:
        aliases:
            - comment_mgmt

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  mgm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
