{
 "title": "Docker via Telegraf",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Number of CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_cpus", "legendFormat": "№ of CPU" }
   ]
  },
  {
   "title": "Total VS Running numbers of containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_n_containers", "legendFormat": "total №" },
    { "expr": "docker_n_containers_running", "legendFormat": "№ of running" }
   ]
  },
  {
   "title": "Mem stats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage/1024/1024",
     "legendFormat": "{{container_name}} usage"
    },
    {
     "expr": "docker_container_mem_max_usage/1024/1024",
     "legendFormat": "{{container_name}} max"
    }
   ]
  },
  {
   "title": "Total number of images",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_n_images", "legendFormat": "№ of images" }
   ]
  },
  {
   "title": "IO read/write stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_blkio_io_service_bytes_recursive_read[10s])",
     "legendFormat": "{{container_name}} read"
    },
    {
     "expr": "rate(docker_container_blkio_io_service_bytes_recursive_write[10s])",
     "legendFormat": "{{container_name}} write"
    }
   ]
  },
  {
   "title": "Net stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes[10s])",
     "legendFormat": "{{container_name}} RX"
    },
    {
     "expr": "rate(docker_container_net_tx_bytes[10s])",
     "legendFormat": "{{container_name}} TX"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}