---
- name: TASK 6 ----------- Generate kubelet Kubernetes configuration files
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars.yml
  vars:


  roles:
    - generate_kubernetes_configs

