FROM alpine:latest

COPY . /app
WORKDIR /app

RUN apk add --no-cache bash python3 && pip3 install -r /app/requirements.txt && rm -rf /var/lib/apk/* && rm -rf /root/.cache/pip

ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

CMD ["python3", "post_app.py"]

